version: '3.9'

services:
  ipinpointapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: